name: Node.js CI

on:
    push:
        branches: [ main ]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: 'Configurando SSH'
              run: |
                echo "${{ secrets.EC2_SSH_KEY }}" > key.pem
                chmod 400 key.pem
                
            # Operaciones para la primera instancia
            - name: 'Eliminar contenido en EC2 (Instancia 1)'
              run: |
                ssh -o StrictHostKeyChecking=no -i key.pem ec2-user@ec2-35-170-201-125.compute-1.amazonaws.com "rm -rf /var/www/html"

            - name: 'Clonar repositorio en EC2 (Instancia 1)'
              run: |
                ssh -o StrictHostKeyChecking=no -i key.pem ec2-user@ec2-35-170-201-125.compute-1.amazonaws.com "git clone https://github.com/Fernandonov21/AWS.git /var/www/html"

            - name: 'Procesar HTML dinámico en EC2 (Instancia 1)'
              run: |
                ssh -o StrictHostKeyChecking=no -i key.pem ec2-user@ec2-35-170-201-125.compute-1.amazonaws.com <<'EOF'
                  HOSTNAME=$(hostname -f)
                  sed -i "s/{{HOSTNAME}}/$HOSTNAME/g" /var/www/html/index.html
                EOF

            # Operaciones para la segunda instancia
            - name: 'Eliminar contenido en EC2 (Instancia 2)'
              run: |
                ssh -o StrictHostKeyChecking=no -i key.pem ec2-user@ec2-35-171-26-51.compute-1.amazonaws.com "rm -rf /var/www/html"

            - name: 'Clonar repositorio en EC2 (Instancia 2)'
              run: |
                ssh -o StrictHostKeyChecking=no -i key.pem ec2-user@ec2-35-171-26-51.compute-1.amazonaws.com "git clone https://github.com/Fernandonov21/AWS.git /var/www/html"

            - name: 'Procesar HTML dinámico en EC2 (Instancia 2)'
              run: |
                ssh -o StrictHostKeyChecking=no -i key.pem ec2-user@ec2-35-171-26-51.compute-1.amazonaws.com <<'EOF'
                  HOSTNAME=$(hostname -f)
                  sed -i "s/{{HOSTNAME}}/$HOSTNAME/g" /var/www/html/index.html
                EOF

            - name: 'Eliminar clave SSH'
              run: rm key.pem
