name: Node.js CI

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        stage: [QA, Production]
        instance:
          - { name: "Instancia 1", address: "ec2-34-238-38-153.compute-1.amazonaws.com" }
          - { name: "Instancia 2", address: "ec2-44-208-35-50.compute-1.amazonaws.com" }

    steps:
      # Configuración inicial
      - name: 'Configurando SSH'
        run: |
          echo "${{ secrets.EC2_SSH_KEY }}" > key.pem
          chmod 400 key.pem

      # Despliegue
      - name: "Eliminar contenido en {{ matrix.stage }} - {{ matrix.instance.name }}"
        run: |
          ssh -o StrictHostKeyChecking=no -i key.pem ec2-user@${{ matrix.instance.address }} "rm -rf /web/AWS"

      - name: "Clonar repositorio en {{ matrix.stage }} - {{ matrix.instance.name }}"
        run: |
          ssh -o StrictHostKeyChecking=no -i key.pem ec2-user@${{ matrix.instance.address }} "git clone https://github.com/Fernandonov21/AWS.git /web/AWS"

      - name: "Procesar HTML dinámico en {{ matrix.stage }} - {{ matrix.instance.name }}"
        run: |
          ssh -o StrictHostKeyChecking=no -i key.pem ec2-user@${{ matrix.instance.address }} <<'EOF'
            HOSTNAME=$(hostname -f)
            sed -i "s/{{HOSTNAME}}/$HOSTNAME/g" /web/AWS/index.html
          EOF

      # Limpieza
      - name: 'Eliminar clave SSH'
        if: always()
        run: rm key.pem
