name: Deployment Workflow

on:
  push:
    branches:
      - main
      - test

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        instance:
          - { name: "Instancia 1", address: "ec2-34-238-38-153.compute-1.amazonaws.com" }
          - { name: "Instancia 2", address: "ec2-44-208-35-50.compute-1.amazonaws.com" }
          - { name: "Instancia 3", address: "ec2-54-164-223-131.compute-1.amazonaws.com" }
        branch: [main, test]

    steps:
      # Configuración inicial de SSH
      - name: Configurando SSH
        run: |
          echo "${{ secrets.EC2_SSH_KEY }}" > key.pem
          chmod 400 key.pem

      # Desplegar en las instancias
      - name: Desplegar en ${{ matrix.branch }} - ${{ matrix.instance.name }}
        run: |
          echo "Desplegando en ${{ matrix.instance.name }} para la rama ${{ matrix.branch }}"

          # Asegurar directorio limpio
          ssh -o StrictHostKeyChecking=no -i key.pem ec2-user@${{ matrix.instance.address }} "
            sudo rm -rf /web/AWS &&
            mkdir -p /web/AWS &&
            sudo chown ec2-user:ec2-user /web/AWS
          "

          # Verificar instalación de Git
          ssh -o StrictHostKeyChecking=no -i key.pem ec2-user@${{ matrix.instance.address }} "
            if ! command -v git &> /dev/null; then
              sudo yum install -y git
            fi
          "

          # Clonar y configurar la rama
          ssh -o StrictHostKeyChecking=no -i key.pem ec2-user@${{ matrix.instance.address }} "
            git clone https://github.com/Fernandonov21/AWS.git /web/AWS &&
            cd /web/AWS &&
            git fetch origin &&
            git checkout ${{ matrix.branch }} &&
            git reset --hard origin/${{ matrix.branch }}
          "

          # Procesar HTML dinámico
          ssh -o StrictHostKeyChecking=no -i key.pem ec2-user@${{ matrix.instance.address }} "
            HOSTNAME=\$(hostname -f) &&
            sed -i 's/{{HOSTNAME}}/\$HOSTNAME/g' /web/AWS/index.html
          "

      # Limpieza
      - name: Eliminar clave SSH
        if: always()
        run: rm key.pem
