name: Node.js CI

on:
  push:
    branches:
      - main
      - test

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Configuración inicial de SSH
      - name: 'Configurando SSH'
        run: |
          echo "${{ secrets.EC2_SSH_KEY }}" > key.pem
          chmod 400 key.pem

      # Configurar entorno de despliegue según la rama
      - name: 'Configurar entorno de despliegue'
        id: config
        run: |
          if [ "${{ github.ref_name }}" == "main" ]; then
            echo "hosts='ec2-user@ec2-44-208-35-50.compute-1.amazonaws.com ec2-user@ec2-34-238-38-153.compute-1.amazonaws.com ec2-user@ec2-54-164-223-131.compute-1.amazonaws.com'" >> $GITHUB_ENV
          elif [ "${{ github.ref_name }}" == "test" ]; then
            echo "hosts='ec2-user@ec2-52-207-211-41.compute-1.amazonaws.com'" >> $GITHUB_ENV
          fi

      # Desplegar en las instancias correspondientes
      - name: 'Desplegar en las instancias'
        run: |
          for host in ${{ env.hosts }}; do
            echo "Desplegando en $host"
            
            # Eliminar contenido existente
            ssh -o StrictHostKeyChecking=no -i key.pem $host "rm -rf /web/AWS"
            
            # Clonar el repositorio
            ssh -o StrictHostKeyChecking=no -i key.pem $host "git clone https://github.com/Fernandonov21/AWS.git /web/AWS"
            
            # Procesar HTML dinámico
            ssh -o StrictHostKeyChecking=no -i key.pem $host <<EOF
            HOSTNAME=\$(hostname -f)
            sed -i "s/{{HOSTNAME}}/\$HOSTNAME/g" /web/AWS/index.html
EOF
          done

      # Limpieza final
      - name: 'Eliminar clave SSH'
        run: rm key.pem
