name: Node.js CI/CD

on:
  push:
    branches:
      - test   # QA
  pull_request:
    branches:
      - main   # Producción solo después de un PR aprobado

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        stage: [QA, Production]
        include:
          # QA
          - stage: QA
            instance_name: "Instancia QA"
            instance_address: "ec2-52-207-211-41.compute-1.amazonaws.com"
          # Producción
          - stage: Production
            instance_name: "Instancia 1"
            instance_address: "ec2-34-238-38-153.compute-1.amazonaws.com"
          - stage: Production
            instance_name: "Instancia 2"
            instance_address: "ec2-44-208-35-50.compute-1.amazonaws.com"
          - stage: Production
            instance_name: "Instancia 3"
            instance_address: "ec2-54-164-223-131.compute-1.amazonaws.com"

    steps:
      # Configuración inicial de SSH
      - name: 'Configurando SSH'
        run: |
          echo "${{ secrets.EC2_SSH_KEY }}" > key.pem
          chmod 400 key.pem

      # Desplegar en las instancias
      - name: "Desplegar en {{ matrix.stage }} - {{ matrix.instance_name }}"
        run: |
          echo "Desplegando en {{ matrix.stage }} - {{ matrix.instance_name }}"
          
          # Instalar Git si no está instalado
          ssh -o StrictHostKeyChecking=no -i key.pem ec2-user@${{ matrix.instance_address }} "sudo yum update -y && sudo yum install -y git || sudo apt update && sudo apt install -y git"
          
          # Eliminar contenido existente
          ssh -o StrictHostKeyChecking=no -i key.pem ec2-user@${{ matrix.instance_address }} "rm -rf /web/AWS"
          
          # Clonar el repositorio
          ssh -o StrictHostKeyChecking=no -i key.pem ec2-user@${{ matrix.instance_address }} "git clone https://github.com/Fernandonov21/AWS.git /web/AWS"
          
          # Procesar HTML dinámico
          ssh -o StrictHostKeyChecking=no -i key.pem ec2-user@${{ matrix.instance_address }} "HOSTNAME=\$(hostname -f) && sed -i 's/{{HOSTNAME}}/\$HOSTNAME/g' /web/AWS/index.html"

      # Limpieza
      - name: 'Eliminar clave SSH'
        if: always()
        run: rm key.pem
